name: Build and Release Maven App

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'  
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package 

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}  
          release_name: Release ${{ github.ref }}  
          body: |
            Release notes for version ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          assets: |
            target/mcMMO.jar
            target/original-mcMMO.jar
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
